### ISSUE TITLE
consider adding further data sources

### ISSUE THREAD

**Issue by AlexMeier99** [SuhasDissa/E-Number-Database#1]
Hi @SuhasDissa,  
I just found your this great repository.

I'd be very grateful if you could consider enhancing the database by including the data of the following sources:

* https://www.fao.org/gsfaonline/additives/index.html
* relevant for users within EU: https://ec.europa.eu/food/food-feed-portal/screen/food-additives/search

Kind regards,
Alex

**Comment by SuhasDissa** [comment]
Hi Alex, I don't hesitate adding more data into this database. But the sources you provided have some problems that stops me from adding those data,

- The data sources are mostly related to legal restrictions of these additives
- The data in those resources are too complex to fit into this database
- The data is spread across hundreds of pages which makes it tedious to add them into this database

This E-Number database is meant to use by average consumers who just want to see if an additive is good or bad and get an idea about their health risks. But your sources are more useful for food producers. If your intention is that, then I kindly suggest you to fork this database and use it as you like.

By the way I'm planing to add a [three tier health rating](https://github.com/SuhasDissa/E-Number-Database/assets/64766434/f59d128b-791e-4166-aede-4fad1bd22d85) for each additive in the future. If you find any useful and reliable sources please let me know.

Kind regards,
Suhas
